---
- hosts: test_rh
  become: True

  tasks:
  - name: Chronyd status
    systemd:
      state: restarted
      daemon_reload: yes
      name: chronyd

  - name: Install nginx
    dnf:
      update_cache: yes
      name: nginx
      state: latest

  - name: Enable nginx daemon
    systemd:
      name: nginx
      enabled: yes
      state: started

  - name: Check nginx configuration
    tags: check
    register: out
    command:
      cmd: nginx -t
      warn: yes

  - name: Nginx configuration state
    tags: check
    debug:
      msg: "{{ out.stderr }}"
