---
- hosts: test_rh
  become: True

  tasks:
  - name: Chronyd status
    systemd:
      state: restarted
      daemon_reload: yes
      name: chronyd

  - name: Install nginx
    dnf:
      update_cache: yes
      name: nginx
      state: latest

  - name: Enable nginx daemon
    systemd:
      name: nginx
      enabled: yes
      state: started
  - name: Check nginx configuration
    shell: 
      cmd: nginx -t
      warn: yes