---
- hosts: test_ubuntu
  become: True

  tasks:
  - name: apt update
    apt:
      update_cache: yes

  name: Install nginx
    apt:
      update_cache: yes
      name: nginx
      state: latest

  - name: Enable nginx daemon
    systemd:
      name: nginx
      enabled: yes
      state: started

  - name: Check nginx configuration
    tags: check
    register: out
    command:
      cmd: nginx -t
      warn: yes

  - name: Nginx configuration state
    tags: check
    debug:
      msg: "{{ out.stderr }}"


  - name: Create user
      user:
        name: kosimovsky
        shell: /bin/bash
        create_home: yes
        groups: sudo
        append: yes
        password: "$6$aQicAVs2.md4WVj$YzaehJCYlPMw6PXwGsTdasv/MqtI7UoOXrg2JB6I/nVYu8pt9suQnm1PzQ50aFjbppeSzK26GridZEhFuUYLq/"

        # vim:ft=ansible:
